SOURCES += \
    msgpack-c/src/unpack.c \
    msgpack-c/src/objectc.c \
    msgpack-c/src/version.c \
    msgpack-c/src/vrefbuffer.c \
    msgpack-c/src/zone.c

HEADERS += \
    msgpack-c/include/msgpack/pack_define.h \
    msgpack-c/include/msgpack/pack_template.h \
    msgpack-c/include/msgpack/unpack_define.h \
    msgpack-c/include/msgpack/unpack_template.h \
    msgpack-c/include/msgpack/util.h \
    msgpack-c/include/msgpack/sysdep.h \
    msgpack-c/include/msgpack/sbuffer.h \
    msgpack-c/include/msgpack/version.h \
    msgpack-c/include/msgpack/vrefbuffer.h \
    msgpack-c/include/msgpack/zbuffer.h \
    msgpack-c/include/msgpack/fbuffer.h \
    msgpack-c/include/msgpack/pack.h \
    msgpack-c/include/msgpack/unpack.h \
    msgpack-c/include/msgpack/object.h \
    msgpack-c/include/msgpack/zone.h \
    msgpack-c/include/msgpack.hpp \
    msgpack-c/include/msgpack_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/bool.hpp \
    msgpack-c/include/msgpack/adaptor/bool_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/char_ptr.hpp \
    msgpack-c/include/msgpack/adaptor/char_ptr_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/cpp11/array.hpp \
    msgpack-c/include/msgpack/adaptor/cpp11/array_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/cpp11/array_char.hpp \
    msgpack-c/include/msgpack/adaptor/cpp11/array_char_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/cpp11/forward_list.hpp \
    msgpack-c/include/msgpack/adaptor/cpp11/forward_list_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/cpp11/tuple.hpp \
    msgpack-c/include/msgpack/adaptor/cpp11/tuple_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/define.hpp \
    msgpack-c/include/msgpack/adaptor/deque.hpp \
    msgpack-c/include/msgpack/adaptor/deque_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/detail/cpp03_define.hpp \
    msgpack-c/include/msgpack/adaptor/detail/cpp03_msgpack_tuple.hpp \
    msgpack-c/include/msgpack/adaptor/detail/cpp03_msgpack_tuple_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/detail/cpp11_define.hpp \
    msgpack-c/include/msgpack/adaptor/detail/cpp11_msgpack_tuple.hpp \
    msgpack-c/include/msgpack/adaptor/detail/cpp11_msgpack_tuple_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/fixint.hpp \
    msgpack-c/include/msgpack/adaptor/fixint_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/float.hpp \
    msgpack-c/include/msgpack/adaptor/float_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/int.hpp \
    msgpack-c/include/msgpack/adaptor/int_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/list.hpp \
    msgpack-c/include/msgpack/adaptor/list_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/map.hpp \
    msgpack-c/include/msgpack/adaptor/map_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/msgpack_tuple.hpp \
    msgpack-c/include/msgpack/adaptor/msgpack_tuple_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/nil.hpp \
    msgpack-c/include/msgpack/adaptor/nil_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/pair.hpp \
    msgpack-c/include/msgpack/adaptor/pair_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/raw.hpp \
    msgpack-c/include/msgpack/adaptor/raw_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/set.hpp \
    msgpack-c/include/msgpack/adaptor/set_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/string.hpp \
    msgpack-c/include/msgpack/adaptor/string_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/tr1/unordered_map.hpp \
    msgpack-c/include/msgpack/adaptor/tr1/unordered_map_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/tr1/unordered_set.hpp \
    msgpack-c/include/msgpack/adaptor/tr1/unordered_set_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/vector.hpp \
    msgpack-c/include/msgpack/adaptor/vector_fwd.hpp \
    msgpack-c/include/msgpack/adaptor/vector_char.hpp \
    msgpack-c/include/msgpack/adaptor/vector_char_fwd.hpp \
    msgpack-c/include/msgpack/cpp_config.hpp \
    msgpack-c/include/msgpack/detail/cpp03_zone.hpp \
    msgpack-c/include/msgpack/detail/cpp11_zone.hpp \
    msgpack-c/include/msgpack/fbuffer.hpp \
    msgpack-c/include/msgpack/object.hpp \
    msgpack-c/include/msgpack/object_fwd.hpp \
    msgpack-c/include/msgpack/pack.hpp \
    msgpack-c/include/msgpack/sbuffer.hpp \
    msgpack-c/include/msgpack/type.hpp \
    msgpack-c/include/msgpack/unpack.hpp \
    msgpack-c/include/msgpack/version.hpp \
    msgpack-c/include/msgpack/versioning.hpp \
    msgpack-c/include/msgpack/vrefbuffer.hpp \
    msgpack-c/include/msgpack/zbuffer.hpp \
    msgpack-c/include/msgpack/zone.hpp

INCLUDEPATH += msgpack-c/include
